version = 3.11.1
maxColumn = 120
lineEndings = unix
importSelectors = singleLine

binPack.parentConstructors = false
project.git = true
runner.dialect = scala3

indent {
  callSite = 2
  defnSite = 2
}

align {
  preset = most
  tokens = [{code = "=>", owner = "Case|Type.Arg.ByName"}, "=", "<-", "->", "%", "%%", "should", "shouldBe", "shouldEqual", "shouldNot", "must"]
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = false
}

spaces {
  beforeContextBoundColon = Never
  inImportCurlyBraces = false
}

rewrite {
  rules = [RedundantBraces, RedundantParens, Imports]
  redundantBraces {
    includeUnitMethods = true
    stringInterpolation = true
    maxBreaks = 100
  }
  imports.sort = ascii
}

newlines {
  sometimesBeforeColonInMethodReturnType = true
  penalizeSingleSelectMultiArgList = false
}
